// template/b/pages/home.vue
<template>
  <main>
    <div>hello world</div>
    <div>
      <a href="/a">goto /a</a>
      <router-link to="/blog">goto /blog</router-link>
    </div>
    <button @click="count++" type="button">
      count is {{ count }}
    </button>
  </main>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const props = defineProps<{
  dsl: any;
}>();

console.debug('renderProps', props);

// biome-ignore lint/correctness/noUnusedVariables: any
const count = ref(0);
</script>

// template/a/remote-template/pages/home.tsx
import { useState } from 'react';
import { Link } from 'react-router';
import { getComp } from '../component-register';
import { useRenderContext } from '../context';
import styles from './home.module.css';

export function Home() {
  const [count, setCount] = useState(0);

  const renderContext = useRenderContext();
  const Button = getComp('SchemaButton') || 'button';

  console.debug('renderContext', renderContext);

  return (
    <main>
      <div className={styles.title}>hello world</div>
      <div>
        <a href="/b/vue">goto /b</a>
        <Link to="/blog">goto /blog</Link>
      </div>
      <Button onClick={() => setCount(count + 1)}>count is {count}</Button>
    </main>
  );
}
